### ISSUE TITLE
Command Line Interface Team 

### ISSUE THREAD

**Issue by johnsc1** [GatorCogitate/cogitate_tool#47]
# General Information
This issue is the new Command Line Interface Team Issue (previously Team Interactions #13  and Basic CLI #19 ) . Our task is now to create a full Command Line Interface for the Cogitate tool. 

# Associated Branches 
[command-line-interface](https://github.com/GatorCogitate/cogitate_tool/tree/command-line-interface)

# Customer Questions
To ask questions to the customer regarding the CLI, please comment under issue #49 . 

# Project Schedule 
## Week Four - Due March 2nd @ 11:59 pm
- [x] Build basic functions of the CLI
- [x] Add documentation for the basic CLI functions
- [x] Test basic functions of the CLI

## Week Five - Due March 9th @ the end of lab
- [x] Add remaining features from the features teams (team and existing individual metrics)
        **see issue #64 for lists of features
- [x] create user input for the merge usernames function in individual metrics
- [x] Ensure all local CLI functions are covered in the test suite 
- [x] Build up the test suite to fullest coverage, add plugins 

## Last Four Days - Due March 13th @ class 
- [x] Uncomment the web interface import statement and main method call 
- [x] Add to and clarify documentation
- [x] Address and close any remaining issues 
- [x] Ensure our branch passes all Travis checks 
- [x] Merge our branch into master

**Comment by johnsc1** [comment]
This week (March 3rd - March 10th) we are going to focus on creating the full framework of the CLI so that it is ready for the features to be integrated, once all of the features are complete and refactored. We will also work with the web interface team to integrate their visualizations into the CLI.

**Comment by santacruzm** [comment]
# Functionality 

**Level 1**

* Team or Individuals 

**Level 2**

* Params
* Calling a Function 
* Results 
* Link to Streamlit (Do you want to view the results in the terminal or on streamlit?)

**Commands we have:**

* Link
* Token
* Repository
* State
* Team
* Individual

**Comment by santacruzm** [comment]
**3/8/20**

Meeting discussion: 

**Tasks**

- Implement existing functions that the user needs to interact with

- Issue #64 contains lists of functions 

- Test Suite (do not test feature functions) Instead focus on testing the local CLI functions

- Document the CLI Interface as we go 

- Implement the Web Interface

**Comment by johnsc1** [comment]
For implementing the **web interface**, we will call their main( ) from very end of the CLI main, returning a URL to the web interface.

**Comment by johnsc1** [comment]
> For implementing the **web interface**, we will call their main( ) from very end of the CLI main, returning a URL to the web interface. The framework with correct file & function names for this already exists in cogitate.py, but we may have to add the option for the user to input if they would like to go to the web interface or not.

I added the while loop and logic for entering the web interface into main( ) of cogitate.py.

**Comment by johnsc1** [comment]
During lab, in addition to adding as many functions as are completed for the individual and team metrics, we will discuss how the address the merge usernames function (one of the functions in the individual metrics lines branch, not yet merged into master at this time). @noorbuchi said creating a function that calls this merge function on a loop might be one way to do this, but we can further discuss this in lab

**Comment by santacruzm** [comment]
**Process**

1. Get raw data

2. Write raw data to the appropriate json file 

3. Call calculate metric function (reads from the json and Returns a Dic)

4. Get PyGitHub Data (Returns a Dic)

5. Merge duplicate usernames

6.  Complete calculations on the data

7. Write to Metrics json

**Comment by gkapfham** [comment]
Can someone please comment on the status of this issue?

**Comment by JMilamber** [comment]
Branch has been merged, Closing Issue.
